apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recommendation-postgres-pvc
  labels:
    app: recommendation-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage