apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
data:
  SERVER_PORT: "{{ .Values.service.port }}"
  DB_HOST: "recommendation-postgres-service"
  DB_PORT: "{{ .Values.database.port }}"