server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${MYSQL_DATABASE:users}
    username: ${MYSQL_USER:spring}
    password: ${MYSQL_ROOT_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true