apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-mysql-service
spec:
  selector:
    app: {{ .Values.name }}-mysql
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.database.port }}